// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbgAiMqPbF2nlSh51Qq6oKIhQ4kqkwJBY',
    appId: '1:714041658323:web:a27450ef8d95ab71903d26',
    messagingSenderId: '714041658323',
    projectId: 'projeto-dsi-4f5f6',
    authDomain: 'projeto-dsi-4f5f6.firebaseapp.com',
    storageBucket: 'projeto-dsi-4f5f6.firebasestorage.app',
    measurementId: 'G-H7V2FPMBNJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcVc-Z2QnenSZqFOtJJwHrS4aw6pd--T4',
    appId: '1:714041658323:android:a27bf7135e07f027903d26',
    messagingSenderId: '714041658323',
    projectId: 'projeto-dsi-4f5f6',
    storageBucket: 'projeto-dsi-4f5f6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDd-Lf36ECyAkU1n9YD76n40Lj3Te-iY58',
    appId: '1:714041658323:ios:2e90570052adc238903d26',
    messagingSenderId: '714041658323',
    projectId: 'projeto-dsi-4f5f6',
    storageBucket: 'projeto-dsi-4f5f6.firebasestorage.app',
    iosBundleId: 'com.example.dsiProject',
  );

}